# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
